// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwjX4_HIg9n2qLHpW0I53qQMxbQHaWgFc',
    appId: '1:550397871514:web:77fdd5607dc870caea6623',
    messagingSenderId: '550397871514',
    projectId: 'arakha-car-rental',
    authDomain: 'arakha-car-rental.firebaseapp.com',
    storageBucket: 'arakha-car-rental.appspot.com',
    measurementId: 'G-0RSVEHZTRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD543X4g9prk_R6HttfDAy1cOk8aBuGChw',
    appId: '1:550397871514:android:2b505f8d6ae93b0cea6623',
    messagingSenderId: '550397871514',
    projectId: 'arakha-car-rental',
    storageBucket: 'arakha-car-rental.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4jefgQgk_4Kq65w5AHm78KJr080eCCio',
    appId: '1:550397871514:ios:4169868bf6745f74ea6623',
    messagingSenderId: '550397871514',
    projectId: 'arakha-car-rental',
    storageBucket: 'arakha-car-rental.appspot.com',
    iosBundleId: 'com.example.startCarRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4jefgQgk_4Kq65w5AHm78KJr080eCCio',
    appId: '1:550397871514:ios:4169868bf6745f74ea6623',
    messagingSenderId: '550397871514',
    projectId: 'arakha-car-rental',
    storageBucket: 'arakha-car-rental.appspot.com',
    iosBundleId: 'com.example.startCarRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwjX4_HIg9n2qLHpW0I53qQMxbQHaWgFc',
    appId: '1:550397871514:web:21503910bcbcfc03ea6623',
    messagingSenderId: '550397871514',
    projectId: 'arakha-car-rental',
    authDomain: 'arakha-car-rental.firebaseapp.com',
    storageBucket: 'arakha-car-rental.appspot.com',
    measurementId: 'G-LJ5RZM3BEG',
  );
}
